-- ============================================================================
-- Esquema Chronos — Supabase / PostgreSQL
-- ============================================================================
-- Tablas, trigger de alta de perfil, función de creación de órdenes y políticas
-- de Row Level Security (RLS). Todos los statements son idempotentes, así que el
-- script puede correrse varias veces sin romper una base existente.
--
-- Orden de aplicación: este archivo primero, luego 02_procesar_pago_mp.sql.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- Tablas
-- ----------------------------------------------------------------------------

-- Perfil extendido del usuario. El id coincide con auth.users(id) de Supabase.
create table if not exists public.usuarios (
  id         uuid primary key references auth.users (id) on delete cascade,
  email      varchar not null,
  nombre     varchar,
  apellido   varchar,
  telefono   varchar,
  direccion  text,
  rol        varchar not null default 'cliente',
  creado_en  timestamp default now()
);

-- Catálogo de relojes.
create table if not exists public.productos (
  id             bigint generated by default as identity primary key,
  nombre         varchar not null,
  descripcion    text,
  precio         numeric not null,
  stock          integer default 0,
  categoria      varchar,
  imagen_url     varchar,
  creado_en      timestamp default now(),
  actualizado_en timestamp default now()
);

-- Carrito persistente por usuario.
create table if not exists public.carrito (
  id           bigint generated by default as identity primary key,
  usuario_id   uuid not null references public.usuarios (id) on delete cascade,
  producto_id  bigint not null references public.productos (id) on delete cascade,
  cantidad     integer not null default 1,
  creado_en    timestamp default now()
);

-- Órdenes de compra. estado: pendiente | pagada | confirmada | enviada | entregada | cancelada
create table if not exists public.ordenes (
  id               bigint generated by default as identity primary key,
  usuario_id       uuid not null references public.usuarios (id) on delete cascade,
  total            numeric not null default 0,
  estado           varchar not null default 'pendiente',
  metodo_pago      varchar,
  referencia_pago  text,
  pagado_en        timestamp,
  creado_en        timestamp default now()
);

-- Ítems de cada orden (snapshot de precio al momento de la compra).
create table if not exists public.orden_items (
  id               bigint generated by default as identity primary key,
  orden_id         bigint not null references public.ordenes (id) on delete cascade,
  producto_id      bigint not null references public.productos (id),
  cantidad         integer not null,
  precio_unitario  numeric not null,
  subtotal         numeric not null
);


-- ----------------------------------------------------------------------------
-- Trigger: al registrarse un usuario en auth.users, crea su perfil en usuarios
-- ----------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.usuarios (id, email)
  values (new.id, new.email)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ----------------------------------------------------------------------------
-- Función: crear_orden_completa
-- ----------------------------------------------------------------------------
-- Crea una orden de forma atómica: valida stock, calcula y verifica el total,
-- inserta la orden y sus ítems, descuenta stock y vacía el carrito. Si algo
-- falla, revierte todo y devuelve el error.
-- La invoca POST /api/ordenes.

create or replace function public.crear_orden_completa(
  p_usuario_id uuid,
  p_items jsonb,
  p_total numeric
)
returns table(orden_id bigint, success boolean, error_msg text)
language plpgsql
as $$
DECLARE
  v_orden_id BIGINT;
  v_item JSONB;
  v_producto_id BIGINT;
  v_cantidad INTEGER;
  v_precio NUMERIC;
  v_stock INTEGER;
  v_subtotal NUMERIC;
  v_total_calculado NUMERIC := 0;
BEGIN
  BEGIN
    IF p_usuario_id IS NULL THEN
      RAISE EXCEPTION 'Usuario inválido.';
    END IF;

    IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
      RAISE EXCEPTION 'El carrito está vacío.';
    END IF;

    -- Primero validamos productos, stock y calculamos total
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
      v_producto_id := (v_item ->> 'producto_id')::BIGINT;
      v_cantidad := (v_item ->> 'cantidad')::INTEGER;

      IF v_producto_id IS NULL OR v_cantidad IS NULL OR v_cantidad <= 0 THEN
        RAISE EXCEPTION 'Item inválido en el carrito.';
      END IF;

      SELECT precio, stock
      INTO v_precio, v_stock
      FROM productos
      WHERE id = v_producto_id;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'El producto % no existe.', v_producto_id;
      END IF;

      IF v_stock < v_cantidad THEN
        RAISE EXCEPTION 'Stock insuficiente para el producto %.', v_producto_id;
      END IF;

      v_subtotal := v_precio * v_cantidad;
      v_total_calculado := v_total_calculado + v_subtotal;
    END LOOP;

    IF ROUND(v_total_calculado, 2) <> ROUND(p_total, 2) THEN
      RAISE EXCEPTION 'El total enviado no coincide con el total calculado.';
    END IF;

    -- Ahora creamos la orden directamente con el total correcto
    INSERT INTO ordenes (usuario_id, total, estado)
    VALUES (p_usuario_id, v_total_calculado, 'pendiente')
    RETURNING id INTO v_orden_id;

    -- Ahora insertamos items y descontamos stock
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
      v_producto_id := (v_item ->> 'producto_id')::BIGINT;
      v_cantidad := (v_item ->> 'cantidad')::INTEGER;

      SELECT precio
      INTO v_precio
      FROM productos
      WHERE id = v_producto_id;

      v_subtotal := v_precio * v_cantidad;

      UPDATE productos
      SET stock = stock - v_cantidad,
          actualizado_en = now()
      WHERE id = v_producto_id;

      INSERT INTO orden_items (
        orden_id,
        producto_id,
        cantidad,
        precio_unitario,
        subtotal
      )
      VALUES (
        v_orden_id,
        v_producto_id,
        v_cantidad,
        v_precio,
        v_subtotal
      );
    END LOOP;

    DELETE FROM carrito
    WHERE usuario_id = p_usuario_id;

    RETURN QUERY SELECT v_orden_id, TRUE, NULL::TEXT;

  EXCEPTION WHEN OTHERS THEN
    RETURN QUERY SELECT NULL::BIGINT, FALSE, SQLERRM;
  END;
END;
$$;


-- ----------------------------------------------------------------------------
-- Row Level Security
-- ----------------------------------------------------------------------------

alter table public.usuarios    enable row level security;
alter table public.productos   enable row level security;
alter table public.carrito     enable row level security;
alter table public.ordenes     enable row level security;
alter table public.orden_items enable row level security;

-- usuarios: cada uno gestiona su propio perfil
drop policy if exists "Usuarios ven su propio perfil" on public.usuarios;
create policy "Usuarios ven su propio perfil" on public.usuarios
  for select using (auth.uid() = id);

drop policy if exists "Usuarios crean su propio perfil" on public.usuarios;
create policy "Usuarios crean su propio perfil" on public.usuarios
  for insert with check (auth.uid() = id);

drop policy if exists "Usuarios actualizan su propio perfil" on public.usuarios;
create policy "Usuarios actualizan su propio perfil" on public.usuarios
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- productos: lectura pública; administración solo para admins
drop policy if exists "Todos pueden ver productos" on public.productos;
create policy "Todos pueden ver productos" on public.productos
  for select using (true);

drop policy if exists "Admins gestionan productos" on public.productos;
create policy "Admins gestionan productos" on public.productos
  for all
  using (exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.rol::text = 'admin'))
  with check (exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.rol::text = 'admin'));

-- carrito: cada usuario, su propio carrito
drop policy if exists "Usuarios ven su carrito" on public.carrito;
create policy "Usuarios ven su carrito" on public.carrito
  for select using (auth.uid() = usuario_id);

drop policy if exists "Usuarios agregan al carrito" on public.carrito;
create policy "Usuarios agregan al carrito" on public.carrito
  for insert with check (auth.uid() = usuario_id);

drop policy if exists "Usuarios actualizan su carrito" on public.carrito;
create policy "Usuarios actualizan su carrito" on public.carrito
  for update using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);

drop policy if exists "Usuarios eliminan su carrito" on public.carrito;
create policy "Usuarios eliminan su carrito" on public.carrito
  for delete using (auth.uid() = usuario_id);

-- ordenes: cada usuario ve/gestiona las suyas; los admins ven y actualizan todas
drop policy if exists "Usuarios ven sus ordenes" on public.ordenes;
create policy "Usuarios ven sus ordenes" on public.ordenes
  for select using (auth.uid() = usuario_id);

drop policy if exists "Usuarios crean sus ordenes" on public.ordenes;
create policy "Usuarios crean sus ordenes" on public.ordenes
  for insert with check (auth.uid() = usuario_id);

-- Los usuarios solo pueden modificar sus órdenes PENDIENTES y sin cambiarles el
-- estado (with check exige que la fila resultante siga 'pendiente'). Lo usa
-- crear-preferencia para guardar metodo_pago/referencia_pago. Marcar una orden
-- como pagada es exclusivo del webhook (procesar_pago_mp, SECURITY DEFINER).
drop policy if exists "Usuarios pueden actualizar sus propias ordenes" on public.ordenes;
drop policy if exists "Usuarios actualizan sus ordenes pendientes" on public.ordenes;
create policy "Usuarios actualizan sus ordenes pendientes" on public.ordenes
  for update
  using (auth.uid() = usuario_id and estado = 'pendiente')
  with check (auth.uid() = usuario_id and estado = 'pendiente');

drop policy if exists "Admins ven todas las ordenes" on public.ordenes;
create policy "Admins ven todas las ordenes" on public.ordenes
  for select using (exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.rol::text = 'admin'));

drop policy if exists "Admins actualizan todas las ordenes" on public.ordenes;
create policy "Admins actualizan todas las ordenes" on public.ordenes
  for update using (exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.rol::text = 'admin'));

-- orden_items: siguen la visibilidad de la orden a la que pertenecen
drop policy if exists "Usuarios ven items de sus ordenes" on public.orden_items;
create policy "Usuarios ven items de sus ordenes" on public.orden_items
  for select using (exists (
    select 1 from ordenes where ordenes.id = orden_items.orden_id and ordenes.usuario_id = auth.uid()
  ));

drop policy if exists "Usuarios crean items de sus ordenes" on public.orden_items;
create policy "Usuarios crean items de sus ordenes" on public.orden_items
  for insert with check (exists (
    select 1 from ordenes where ordenes.id = orden_items.orden_id and ordenes.usuario_id = auth.uid()
  ));

drop policy if exists "Admins ven todos los items de ordenes" on public.orden_items;
create policy "Admins ven todos los items de ordenes" on public.orden_items
  for select using (exists (select 1 from usuarios where usuarios.id = auth.uid() and usuarios.rol::text = 'admin'));
